package main.java;

/**
 * Created by Jacob on 2/12/2016.
 */
public enum SquareType
{
    FLOOR, FLOORMAIN, WALL, WINDOW, WINDOWMAIN, DOOR, DOORMAIN, BED, BEDMAIN, SOFA, SOFAMAIN, DESK,
    DESKMAIN, DESKCHAIR, DESKCHAIRMAIN, WALLTV, WALLTVMAIN, SOFATABLE, SOFATABLEMAIN, MAT, MATMAIN, BOOKSHELF, BOOKSHELFMAIN
}
